#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝                       

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#5c5c5c"
bspc config normal_border_color "#2e2e2e"
bspc config focus_follows_pointer true

# AutoStart Applications
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --config $HOME/.config/picom/picom.conf &
dunst &
mpd &
~/.config/polybar/launch.sh &
~/.config/bspwm/scripts/locknsleep.sh &
numlockx on &
xsetroot -cursor_name left_ptr &

# Open applications on specific workspaces
bspc rule -a nekoray desktop=^10

# Open specific applications in floating mode
bspc rule -a nekoray state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a ncmpcpp state=floating
bspc rule -a update state=floating

